config/routes.rb
Rails.application.routes.draw do

  resources :planet_materials
  resources :questions, only: [:index, :show]
  resources :materials, only: [:index]
  resources :activities
  resources :planets, only: [:index, :show, :new, :create]
  resources :users, only: [:index, :show, :new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  post '/questions', to: 'questions#show'
  patch 'recieve_answer', to: 'questions#recieve_answer'
  get '/success', to: 'questions#success'
  get '/failure', to: 'questions#failure'


end

app/models/activity.rb
class Activity < ApplicationRecord
  has_many :planets
  has_many :questions

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/material.rb
class Material < ApplicationRecord
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :planet_materials
  belongs_to :user
  has_many :activities
  has_many :questions, through: :activities

end

app/models/planet_material.rb
class PlanetMaterial < ApplicationRecord
  belongs_to :material
  belongs_to :planet
  before_create :default_values
  def default_values
    self.total_units = 0
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :activity
  has_many :materials
  
end

app/models/resource.rb
class Resource < ApplicationRecord
  belongs_to :planet
  has_many :questions
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :planets
  has_secure_password

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @activities = Activity.all
    @questions = Question.all
  end

  def show
    @activity = Activity.find(params[:id])
    @questions = Question.all.select {|q| q.id == @activity.id }
    
  end

  
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

    
    def index 
        @planets = Planet.all
    end

    def show 
        @planet = Planet.find(params[:id])
    end

    def new 
        @planet = Planet.new(:stage => 1, :high_score => 0) 
    end

    def create 
        @planet = Planet.create(planet_params)
        redirect_to planet_path(@planet)
    end

    private

    def planet_params
        params.require(:planet).permit(:planet_name, :stage, :high_score, :user_id)
      end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
   
  end

  def show
    @questions = Question.all.select {|q| q.activity.activity_name == params[:commit] }
    @chosen_question = @questions.sample

    
  end

  
  def recieve_answer
    @planet = Planet.find(1)
    @question = Question.find_by_answer(params[:solution])
    @activity = @question.activity
    
    
   if params[:solution] == params[:commit]
    @success_reward = PlanetMaterial.find_or_create_by(planet_id: @planet.id, material_id: @question.material_id)
    @success_reward.total_units += @activity.base_reward
    @success_reward.save
    
    redirect_to '/success' 
   else
    redirect_to '/failure'
   end
    
  end

  def success

  end

  def failure

  end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index 
        @users = User.all
    end

    def show 
        @user = User.find(params[:id])
    end

    def new 
        @user = User.new
    end

    def create 
        @user = User.create(user_params)
        redirect_to user_path(@user)
    end

    private

    def user_params 
        params.require(:user).permit(:username, :password_digest, :native_species)
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home

  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/planet_materials_helper.rb
module PlanetMaterialsHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/index.html.erb
<h2>Activities</h2>

<ul>
 <% @activities.each do |a| %>
   <li>
     <%= a.activity_name %>
     <%= form_tag 'questions', method: "post" do %>
     <%= submit_tag "#{a.activity_name}" %>
     <% end %> 
   </li>
   <br>
 <% end %>
</ul>

app/views/planets/index.html.erb
<h2>Planets In Orbit</h2>

<ul>
  <% @planets.each do |planet| %>
    <li>
      <%= button_to(planet.planet_name, planet, :method => "get" ) %>
        <ul><br>
            <li><%= "High Score: #{planet.high_score}" %></li>
            <li><%= "Stage: #{planet.stage}" %></li>
        </ul>
    </li>
    <br>
  <% end %>
</ul>

<%= button_to('build your planet', new_planet_path, :method => "get", class: "btn") %>

app/views/planets/new.html.erb
<%= form_for @planet, :html=>{:class=> "form"} do |f| %>
    <%= f.label :planet_name %><br><br>
    <%= f.text_field :planet_name %><br><br>
    <%= f.label :stage %><br><br>
    <%= f.text_field :stage %><br><br>
    <%= f.label :high_score %><br><br>
    <%= f.text_field :high_score %><br><br>
    <%= f.label :user_id %><br><br>
    <%= f.text_field :user_id%><br><br><br>
    <%= f.submit 'Create Planet' %><br><br>
<% end %>

app/views/planets/show.html.erb
<h1><%= @planet.planet_name %></h1>

app/views/questions/failure.html.erb
<p>Failure!</p>

app/views/questions/show.html.erb
<%= form_for @chosen_question, :url => { :action => :recieve_answer } do |f|%>
<%= @chosen_question.content %>
<%= hidden_field_tag 'solution', "#{@chosen_question.answer}"%>
<div class='choice_a'>
<%= f.submit "#{@chosen_question.choice_a}"%>
</div>
<div class='choice_b'>
<%= f.submit "#{@chosen_question.choice_b}"%>
</div>
<div class='choice_c'>
<%= f.submit "#{@chosen_question.choice_c}"%>
</div>
<div class='choice_d'>
<%= f.submit "#{@chosen_question.choice_d}"%>
</div>


<% end %>

app/views/questions/success.html.erb
<p>Successful!</p>

app/views/users/index.html.erb
<h2>Active Users</h2>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= button_to(user.username, user, :method => "get") %>
        <ul><br>
            <li><%= "Native Species: #{user.native_species}" %></li>
        </ul>
    </li>
    <br>
  <% end %>
</ul>

<%= button_to('sign up', new_user_path, :method => "get", class: "btn") %>

app/views/users/new.html.erb
<%= form_for @user,:html=>{:class=> "form1"} do |f| %>
    <%= f.label :username %><br><br>
    <%= f.text_field :username %><br><br>
    <%= f.label :password_digest %><br><br>
    <%= f.text_field :password_digest %><br><br>
    <%= f.label :native_species %><br><br>
    <%= f.text_field :native_species %><br><br>
    <%= f.submit 'Sign Up' %><br><br>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %><br></h1>
<%= button_to("create planet", new_planet_path, :method => "get") %>